{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-db-helper-cm
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
data:
  setup.sql: |
    {{- if and .Values.databaseDrop.enabled }}
    DROP OWNED BY {{ .Values.databaseConnection.user }};
    {{- end }}
    CREATE USER {{ .Values.databaseConnection.user }} WITH PASSWORD '{{ .Values.databaseConnection.password }}';
    CREATE DATABASE {{ .Values.databaseConnection.database }} WITH OWNER {{ .Values.databaseConnection.user }}
      ENCODING 'UTF8' LC_COLLATE='{{ .Values.databaseConnection.lang }}' LC_CTYPE='{{ .Values.databaseConnection.lang }}' TEMPLATE template0;
{{- end }}
