apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jira-software.fullname" . }}-cm
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envVars }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
