---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira-software.fullname" . }}
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 8080
  selector:
    {{- include "jira-software.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira-software.fullname" . }}-headless
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
  selector:
    {{- include "jira-software.selectorLabels" . | nindent 4 }}
